
services:
  openwpm:
    container_name: openwpm-10
    build: .
    environment:
      VNC_PASSWORD_FILE: /run/secrets/vnc_password
    secrets:
      - vnc_password
    ports:
      - '5900:5900' # VNC


secrets:
  vnc_password:
    file: secrets/vnc_password.txt
